Change require statment so puppet can find the libary.
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Virtual Query, Could not autoload puppet/type/firewalld_zone: Could not autoload puppet/provider/firewalld_zone/zoneprovider: cannot load such file -- puppet/provider/firewalld at firewalld/manifests/init.pp:51:27 on node server3